
require:
  - rubocop

AllCops:
 TargetRubyVersion: 3.0
 Exclude:
   - 'bin/**/*'
   - 'vendor/**/*'
   - 'db/**/*'
   - 'config/**/*'
   - 'script/**/*'
   - 'spec/rails_helper.rb'

# Trabalhamos bastante com testes como a documentação viva do projeto então
# desabilitamos a Cop de documentação com comentário
Documentation:
 Enabled: false

# Esta é uma Cop polêmica, pois pode ajudar na performance. Isso se tornará
# padrão no Ruby 3, mas deixamos a seu critério. Caso deseje manter esta Cop,
# basta remover estas linhas
Style/FrozenStringLiteralComment:
 Enabled: false


# Costumamos usar o padrão do RuboCop, mas caso queira alterar o tamanho de
# caracteres de uma linha, você pode fazê-lo aqui
Metrics/LineLength:
  Max: 80

AsciiComments:
  Enabled: false