version: '3'
services: 
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    # depends_on: 
    #   - db
    # db:
    #   image: alpine:3.14
    #   environment: 
    #     - POSTGRES_USER=admin
    #     - POSTGRES_PASSWORD=1234
    #   volumes:
    #     - db-data:/var/lib/postgresql/data